### ISSUE TITLE
Move left margin from the demo wrapper to the demos themselves

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ciena-frost.github.io#36]
The wrapper around the component demos inserts a `margin-left: 20px` which requires individual demos to have no left margin/padding, which makes them look quite horrible when viewed on their own. Each demo should be responsible for providing the left margin so they are still usable on their own w/o needing to view them through the main doc site to have decent padding/margin.

**Comment by EWhite613** [comment]
Sounds good. I'll tackle this on Monday

**Comment by EWhite613** [comment]
Should be good to go once all [these](https://github.com/search?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AEWhite613+) are merged and then ill merge this in https://github.com/EWhite613/ciena-frost.github.io/commit/ed9759a9fb2765af0e4710d90f56185e0034280b

**Comment by EWhite613** [comment]
Done
